alias: Stop doorbell call if door or gate was opened
mode: single
trigger:
  - platform: state
    entity_id:
      - cover.doorbell_door
      - cover.street_gate
    from: closed
    to: open
conditions:
  - condition: state
    entity_id: input_boolean.doorbell_calling
    state: "on"
action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.doorbell_calling
