alias: Stop ringing tablet if doorbell answered
mode: single
trigger:
  - platform: state
    entity_id:
      - input_boolean.doorbell_calling
    from: "on"
    to: "off"
action:
  - action: media_player.media_stop
    data:
      entity_id: media_player.kitchen_tablet
